# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 641)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dashboard = QtWidgets.QWidget(self.centralwidget)
        self.dashboard.setStyleSheet("#dashboard {\n"
"        border-radius: 4px;\n"
"            border: 0.5px solid rgb(180, 180, 180);\n"
"        background-color: white;\n"
"    }")
        self.dashboard.setObjectName("dashboard")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dashboard)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.connect_to_iot_button = QtWidgets.QPushButton(self.dashboard)
        self.connect_to_iot_button.setStyleSheet("#connect_to_iot_button {\n"
"            background-color: white; \n"
"        border: 0.5px solid rgb(180, 180, 180);\n"
"            color: black;\n"
"        border-radius: 4px\n"
"    }\n"
"#connect_to_iot_button:hover { \n"
"        background-color: lightgray; \n"
"    }\n"
"#connect_to_iot_button:pressed{\n"
"        background-color:gray;\n"
"    }")
        self.connect_to_iot_button.setObjectName("connect_to_iot_button")
        self.verticalLayout_2.addWidget(self.connect_to_iot_button)
        self.check_connection_button = QtWidgets.QPushButton(self.dashboard)
        self.check_connection_button.setStyleSheet("#check_connection_button {\n"
"            background-color: white; \n"
"        border: 0.5px solid rgb(180, 180, 180);\n"
"            color: black;\n"
"        border-radius: 4px\n"
"    }\n"
"#check_connection_button:hover { \n"
"        background-color: lightgray; \n"
"    }\n"
"#check_connection_button:pressed{\n"
"        background-color:gray;\n"
"    }")
        self.check_connection_button.setObjectName("check_connection_button")
        self.verticalLayout_2.addWidget(self.check_connection_button)
        self.submit_button = QtWidgets.QPushButton(self.dashboard)
        self.submit_button.setStyleSheet("#submit_button {\n"
"            background-color: white; \n"
"        border: 0.5px solid rgb(180, 180, 180);\n"
"            color: black;\n"
"        border-radius: 4px\n"
"    }\n"
"#submit_button:hover { \n"
"        background-color: lightgray; \n"
"    }\n"
"#submit_button:pressed{\n"
"        background-color:gray;\n"
"    }")
        self.submit_button.setObjectName("submit_button")
        self.verticalLayout_2.addWidget(self.submit_button)
        self.disconnect_button = QtWidgets.QPushButton(self.dashboard)
        self.disconnect_button.setStyleSheet("#disconnect_button {\n"
"            background-color: white; \n"
"        border: 0.5px solid rgb(180, 180, 180);\n"
"            color: black;\n"
"        border-radius: 4px\n"
"    }\n"
"#disconnect_button:hover { \n"
"        background-color: lightgray; \n"
"    }\n"
"#disconnect_button:pressed{\n"
"        background-color:gray;\n"
"    }")
        self.disconnect_button.setObjectName("disconnect_button")
        self.verticalLayout_2.addWidget(self.disconnect_button)
        self.random_button = QtWidgets.QPushButton(self.dashboard)
        self.random_button.setStyleSheet("#random_button {\n"
"            background-color: white; \n"
"        border: 0.5px solid rgb(180, 180, 180);\n"
"            color: black;\n"
"        border-radius: 4px\n"
"    }\n"
"#random_button:hover { \n"
"        background-color: lightgray; \n"
"    }\n"
"#random_button:pressed{\n"
"        background-color:gray;\n"
"    }")
        self.random_button.setObjectName("random_button")
        self.verticalLayout_2.addWidget(self.random_button)
        self.verticalLayout.addWidget(self.dashboard)
        self.panel_window = QtWidgets.QWidget(self.centralwidget)
        self.panel_window.setStyleSheet("")
        self.panel_window.setObjectName("panel_window")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.panel_window)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_4 = QtWidgets.QWidget(self.panel_window)
        self.widget_4.setStyleSheet("\n"
"        border-radius: 4px;\n"
"            border: 0.5px solid rgb(180, 180, 180);\n"
"        background-color: white")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_1 = QtWidgets.QLabel(self.widget_4)
        self.label_1.setMinimumSize(QtCore.QSize(0, 0))
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_3.addWidget(self.label_1)
        self.status_1 = QtWidgets.QLabel(self.widget_4)
        self.status_1.setMinimumSize(QtCore.QSize(0, 0))
        self.status_1.setMaximumSize(QtCore.QSize(25, 16777215))
        self.status_1.setText("")
        self.status_1.setObjectName("status_1")
        self.horizontalLayout_3.addWidget(self.status_1)
        self.lcdNumber_1 = QtWidgets.QLCDNumber(self.widget_4)
        self.lcdNumber_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lcdNumber_1.setStyleSheet("background-color: black;")
        self.lcdNumber_1.setSmallDecimalPoint(False)
        self.lcdNumber_1.setProperty("value", 0.0)
        self.lcdNumber_1.setObjectName("lcdNumber_1")
        self.horizontalLayout_3.addWidget(self.lcdNumber_1)
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.doubleSpinBox_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinBox_1.setKeyboardTracking(True)
        self.doubleSpinBox_1.setDecimals(1)
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_1)
        self.device_1_connect_button = QtWidgets.QPushButton(self.widget_4)
        self.device_1_connect_button.setStyleSheet("#device_1_connect_button {\n"
"            background-color: white; \n"
"        border: 0.5px solid rgb(180, 180, 180);\n"
"            color: black;\n"
"        border-radius: 4px\n"
"    }\n"
"#device_1_connect_button:hover { \n"
"        background-color: lightgray; \n"
"    }\n"
"#device_1_connect_button:pressed{\n"
"        background-color:gray;\n"
"    }")
        self.device_1_connect_button.setObjectName("device_1_connect_button")
        self.horizontalLayout_3.addWidget(self.device_1_connect_button)
        self.device_1_disconnect_button = QtWidgets.QPushButton(self.widget_4)
        self.device_1_disconnect_button.setStyleSheet("#device_1_disconnect_button {\n"
"            background-color: white; \n"
"        border: 0.5px solid rgb(180, 180, 180);\n"
"            color: black;\n"
"        border-radius: 4px\n"
"    }\n"
"#device_1_disconnect_button:hover { \n"
"        background-color: lightgray; \n"
"    }\n"
"#device_1_disconnect_button:pressed{\n"
"        background-color:gray;\n"
"    }")
        self.device_1_disconnect_button.setObjectName("device_1_disconnect_button")
        self.horizontalLayout_3.addWidget(self.device_1_disconnect_button)
        self.verticalLayout_7.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.panel_window)
        self.widget_3.setStyleSheet("\n"
"        border-radius: 4px;\n"
"            border: 0.5px solid rgb(180, 180, 180);\n"
"        background-color: white\n"
"    ")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.status_2 = QtWidgets.QLabel(self.widget_3)
        self.status_2.setMinimumSize(QtCore.QSize(0, 0))
        self.status_2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.status_2.setText("")
        self.status_2.setObjectName("status_2")
        self.horizontalLayout_2.addWidget(self.status_2)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.widget_3)
        self.lcdNumber_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lcdNumber_2.setStyleSheet("background-color: black")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout_2.addWidget(self.lcdNumber_2)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.doubleSpinBox_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_2)
        self.device_2_connect_button = QtWidgets.QPushButton(self.widget_3)
        self.device_2_connect_button.setStyleSheet("#device_2_connect_button {\n"
"            background-color: white; \n"
"        border: 0.5px solid rgb(180, 180, 180);\n"
"            color: black;\n"
"        border-radius: 4px\n"
"    }\n"
"#device_2_connect_button:hover { \n"
"        background-color: lightgray; \n"
"    }\n"
"#device_2_connect_button:pressed{\n"
"        background-color:gray;\n"
"    }")
        self.device_2_connect_button.setObjectName("device_2_connect_button")
        self.horizontalLayout_2.addWidget(self.device_2_connect_button)
        self.device_2_disconnect_button = QtWidgets.QPushButton(self.widget_3)
        self.device_2_disconnect_button.setStyleSheet("#device_1_disconnect_button {\n"
"            background-color: white; \n"
"        border: 0.5px solid rgb(180, 180, 180);\n"
"            color: black;\n"
"        border-radius: 4px\n"
"    }\n"
"#device_1_disconnect_button:hover { \n"
"        background-color: lightgray; \n"
"    }\n"
"#device_1_disconnect_button:pressed{\n"
"        background-color:gray;\n"
"    }")
        self.device_2_disconnect_button.setObjectName("device_2_disconnect_button")
        self.horizontalLayout_2.addWidget(self.device_2_disconnect_button)
        self.verticalLayout_7.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(self.panel_window)
        self.widget_5.setStyleSheet("\n"
"        border-radius: 4px;\n"
"            border: 0.5px solid rgb(180, 180, 180);\n"
"        background-color: white\n"
"    ")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.status_3 = QtWidgets.QLabel(self.widget_5)
        self.status_3.setMinimumSize(QtCore.QSize(0, 0))
        self.status_3.setMaximumSize(QtCore.QSize(25, 16777215))
        self.status_3.setText("")
        self.status_3.setObjectName("status_3")
        self.horizontalLayout_4.addWidget(self.status_3)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.widget_5)
        self.lcdNumber_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lcdNumber_3.setStyleSheet("background-color: black")
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.horizontalLayout_4.addWidget(self.lcdNumber_3)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.widget_5)
        self.doubleSpinBox_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinBox_3.setDecimals(1)
        self.doubleSpinBox_3.setMaximum(1.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_3)
        self.device_3_connect_button = QtWidgets.QPushButton(self.widget_5)
        self.device_3_connect_button.setStyleSheet("#device_3_connect_button {\n"
"            background-color: white; \n"
"        border: 0.5px solid rgb(180, 180, 180);\n"
"            color: black;\n"
"        border-radius: 4px\n"
"    }\n"
"#device_3_connect_button:hover { \n"
"        background-color: lightgray; \n"
"    }\n"
"#device_3_connect_button:pressed{\n"
"        background-color:gray;\n"
"    }")
        self.device_3_connect_button.setObjectName("device_3_connect_button")
        self.horizontalLayout_4.addWidget(self.device_3_connect_button)
        self.device_3_disconnect_button = QtWidgets.QPushButton(self.widget_5)
        self.device_3_disconnect_button.setStyleSheet("#device_1_disconnect_button {\n"
"            background-color: white; \n"
"        border: 0.5px solid rgb(180, 180, 180);\n"
"            color: black;\n"
"        border-radius: 4px\n"
"    }\n"
"#device_1_disconnect_button:hover { \n"
"        background-color: lightgray; \n"
"    }\n"
"#device_1_disconnect_button:pressed{\n"
"        background-color:gray;\n"
"    }")
        self.device_3_disconnect_button.setObjectName("device_3_disconnect_button")
        self.horizontalLayout_4.addWidget(self.device_3_disconnect_button)
        self.verticalLayout_7.addWidget(self.widget_5)
        self.verticalLayout.addWidget(self.panel_window)
        self.info_board_window = QtWidgets.QWidget(self.centralwidget)
        self.info_board_window.setStyleSheet("        border-radius: 4px;\n"
"            border: 0.5px solid rgb(180, 180, 180);\n"
"        background-color: white")
        self.info_board_window.setObjectName("info_board_window")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.info_board_window)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_board = QtWidgets.QTextEdit(self.info_board_window)
        self.info_board.setObjectName("info_board")
        self.horizontalLayout.addWidget(self.info_board)
        self.verticalLayout.addWidget(self.info_board_window)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connect_to_iot_button.setText(_translate("MainWindow", "Push to create connection"))
        self.check_connection_button.setText(_translate("MainWindow", "Push to check connection"))
        self.submit_button.setText(_translate("MainWindow", "submit"))
        self.disconnect_button.setText(_translate("MainWindow", "Push to disconnect"))
        self.random_button.setText(_translate("MainWindow", "Generate random value"))
        self.label_1.setText(_translate("MainWindow", "TextLabel"))
        self.device_1_connect_button.setText(_translate("MainWindow", "Connect"))
        self.device_1_disconnect_button.setText(_translate("MainWindow", "Disconnect"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.device_2_connect_button.setText(_translate("MainWindow", "Connect"))
        self.device_2_disconnect_button.setText(_translate("MainWindow", "Disconnect"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.device_3_connect_button.setText(_translate("MainWindow", "Connect"))
        self.device_3_disconnect_button.setText(_translate("MainWindow", "Disconnect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
